// Package api holds the check that keeps the public surface deliberate.
//
// Go controls exporting with one rule: an identifier is exported when it
// starts with a capital letter. That means the surface can grow by accident,
// a field at a time, and nothing says so. api.txt at the repo root is that
// surface written down, and this test fails when the code and the file
// disagree, so adding to the API is a diff a reviewer sees:
//
//	go generate ./internal/api    # or: go test ./internal/api -update
package api

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

//go:generate go test . -update

var update = flag.Bool("update", false, "rewrite api.txt from the source")

// packages are the ones users import. Anything under examples or cmd is a
// command, and internal is unimportable outside this module, so neither has
// a surface to keep.
var packages = []string{"work", "history", "world", "cli", "units", "ui", "interpreter"}

const goldenFile = "../../api.txt"

func TestPublicAPIIsWhatWeSaidItWas(t *testing.T) {
	want, err := surface()
	if err != nil {
		t.Fatal(err)
	}

	if *update {
		if err := os.WriteFile(goldenFile, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", goldenFile)
		return
	}

	got, err := os.ReadFile(goldenFile)
	if err != nil {
		t.Fatalf("%v\nrun `go generate ./internal/api` to create it", err)
	}
	if string(got) == want {
		return
	}
	t.Errorf("the exported API is not what api.txt says.\n%s\n"+
		"if the change is intended, run `go generate ./internal/api` and commit the diff",
		diff(string(got), want))
}

// surface renders every exported identifier of every published package.
func surface() (string, error) {
	var b strings.Builder
	b.WriteString("# The exported API, generated by `go generate ./internal/api`.\n" +
		"# A change here is a change to what users can call. Review it as one.\n")
	for _, pkg := range packages {
		lines, err := exported(filepath.Join("../..", pkg))
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\npackage %s\n", pkg)
		for _, l := range lines {
			fmt.Fprintf(&b, "\t%s\n", l)
		}
	}
	return b.String(), nil
}

func exported(dir string) ([]string, error) {
	fset := token.NewFileSet()
	// ParseDir is deprecated in favor of golang.org/x/tools/go/packages, which
	// would add a dependency to pull in one build-tag-unaware directory scan.
	// This package has no build tags, so the gap ParseDir's deprecation warns
	// about does not apply here.
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool { //nolint:staticcheck
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil, err
	}
	var lines []string
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				lines = append(lines, declLines(decl)...)
			}
		}
	}
	sort.Strings(lines)
	return lines, nil
}

func declLines(decl ast.Decl) []string {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		return funcLines(d)
	case *ast.GenDecl:
		var lines []string
		for _, spec := range d.Specs {
			lines = append(lines, specLines(d.Tok, spec)...)
		}
		return lines
	}
	return nil
}

func funcLines(d *ast.FuncDecl) []string {
	if !d.Name.IsExported() {
		return nil
	}
	sig := strings.TrimPrefix(types.ExprString(d.Type), "func")
	// types.ExprString renders a FuncType's parameters and results but not its
	// own TypeParams. A generic free function would otherwise print
	// identically to a non-generic one of the same name, hiding exactly the
	// kind of change this file exists to catch.
	tparams := typeParamString(d.Type.TypeParams)
	if d.Recv == nil || len(d.Recv.List) == 0 {
		return []string{fmt.Sprintf("func %s%s%s", d.Name.Name, tparams, sig)}
	}
	recv := types.ExprString(d.Recv.List[0].Type)
	if !exportedName(strings.TrimPrefix(recv, "*")) {
		return nil // a method on a type users cannot name is not surface
	}
	// Methods sort with their type, not among the package's functions.
	return []string{fmt.Sprintf("type %s method (%s) %s%s",
		strings.TrimPrefix(recv, "*"), recv, d.Name.Name, sig)}
}

func specLines(tok token.Token, spec ast.Spec) []string {
	switch s := spec.(type) {
	case *ast.ValueSpec:
		var lines []string
		for i, name := range s.Names {
			if !name.IsExported() {
				continue
			}
			line := fmt.Sprintf("%s %s", tok, name.Name)
			switch {
			case s.Type != nil:
				line += " " + types.ExprString(s.Type)
			case i < len(s.Values):
				if lit, ok := s.Values[i].(*ast.BasicLit); ok {
					line += " = " + lit.Value
				}
			}
			lines = append(lines, line)
		}
		return lines
	case *ast.TypeSpec:
		if !s.Name.IsExported() {
			return nil
		}
		return typeLines(s)
	}
	return nil
}

func typeLines(s *ast.TypeSpec) []string {
	// A generic type's own TypeParams (Step[T]'s [T any]) is likewise not
	// part of what types.ExprString prints for its fields or methods, so it
	// is folded into the name once here rather than dropped everywhere.
	name := s.Name.Name + typeParamString(s.TypeParams)
	switch t := s.Type.(type) {
	case *ast.StructType:
		lines := []string{fmt.Sprintf("type %s struct", name)}
		for _, f := range t.Fields.List {
			for _, fn := range f.Names {
				if fn.IsExported() {
					lines = append(lines, fmt.Sprintf("type %s field %s %s",
						name, fn.Name, types.ExprString(f.Type)))
				}
			}
		}
		return lines
	case *ast.InterfaceType:
		lines := []string{fmt.Sprintf("type %s interface", name)}
		for _, m := range t.Methods.List {
			for _, mn := range m.Names {
				if mn.IsExported() {
					lines = append(lines, fmt.Sprintf("type %s interface-method %s%s",
						name, mn.Name, strings.TrimPrefix(types.ExprString(m.Type), "func")))
				}
			}
		}
		return lines
	default:
		return []string{fmt.Sprintf("type %s %s", name, types.ExprString(s.Type))}
	}
}

// typeParamString renders a generic declaration's own type parameter list,
// "[T any]", which neither types.ExprString nor the TypeSpec/FuncDecl name
// includes on its own. It returns "" for a non-generic declaration, so every
// other call site is unaffected.
func typeParamString(tp *ast.FieldList) string {
	if tp == nil || len(tp.List) == 0 {
		return ""
	}
	var parts []string
	for _, f := range tp.List {
		constraint := types.ExprString(f.Type)
		for _, n := range f.Names {
			parts = append(parts, n.Name+" "+constraint)
		}
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func exportedName(s string) bool {
	return s != "" && s[0] >= 'A' && s[0] <= 'Z'
}

// diff reports the lines that were added and removed, which is what a reviewer
// needs to see rather than two whole files.
func diff(old, new string) string {
	was := map[string]bool{}
	for _, l := range strings.Split(old, "\n") {
		was[l] = true
	}
	now := map[string]bool{}
	for _, l := range strings.Split(new, "\n") {
		now[l] = true
	}
	var b strings.Builder
	for _, l := range strings.Split(new, "\n") {
		if l != "" && !was[l] {
			fmt.Fprintf(&b, "  + %s\n", strings.TrimSpace(l))
		}
	}
	for _, l := range strings.Split(old, "\n") {
		if l != "" && !now[l] {
			fmt.Fprintf(&b, "  - %s\n", strings.TrimSpace(l))
		}
	}
	return b.String()
}
